### ISSUE TITLE
[Bug]: Middleware does not work

### ISSUE THREAD

**Issue by ryssbowh** [kalynasolutions/laravel-tus#22]
### What happened?

The middleware defined in config is never applied to the routes, as the method `middleware` is called twice in `routes/tus.php`, this is an intended behavior in laravel it seems : https://github.com/laravel/framework/issues/28139

Removing the middleware call [here](https://github.com/kalynasolutions/laravel-tus/blob/main/routes/tus.php#L11) makes it work.

### How to reproduce the bug

Add a middleware in config, dump and die in that middleware and call the url, it does not die
Remove line 11 in the routes and call the url, it does die

### Package Version

1.1.1

### PHP Version

8.2.0

### Laravel Version

10.41.0

**Comment by ArthurPatriot** [comment]
Hello @ryssbowh , i will check today. Thank you for your contribution.

**Comment by ArthurPatriot** [comment]
Done)
