### ISSUE TITLE
[Bug]: FileUploadBeforeCreated is missing in v1.2.1

### ISSUE THREAD

**Issue by QuentinGab** [kalynasolutions/laravel-tus#29]
### What happened?

The file `KalynaSolutions\Tus\Events\FileUploadBeforeCreated` is missing in the v1.2.1 release. 

### How to reproduce the bug

Install v1.2.1
Upload a file

### Package Version

1.2.1

### PHP Version

8.3.0

### Laravel Version

11.30.0

**Comment by QuentinGab** [comment]
#28 has not be included in v1.2.1

**Comment by ArthurPatriot** [comment]
Fixed in v1.2.2
